"""activity created_at

Revision ID: 163318be8852
Revises: 953921a03bff
Create Date: 2022-06-03 17:30:01.279320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163318be8852'
down_revision = '953921a03bff'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'created_at')
    # ### end Alembic commands ###
