"""rename user image field

Revision ID: 40e8ac22dd25
Revises: 89871bf0f61e
Create Date: 2022-06-02 22:32:21.566388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e8ac22dd25'
down_revision = '89871bf0f61e'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.String(length=120), nullable=True))
    op.drop_column('user', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('user', 'image')
    # ### end Alembic commands ###
