"""activity.cost data type string

Revision ID: 61c50c08439e
Revises: 6e026a377aa3
Create Date: 2022-06-01 20:39:41.418329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c50c08439e'
down_revision = '6e026a377aa3'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'cost')
    op.add_column('activity', sa.Column('cost', sa.String(20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    op.drop_column('activity', 'cost')
    op.add_column('activity', sa.Column('cost', sa.Float, nullable=True))
    # ### end Alembic commands ###
