"""activity column place_id

Revision ID: 6e026a377aa3
Revises: d7e69c74374c
Create Date: 2022-06-01 20:31:27.311735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e026a377aa3'
down_revision = 'd7e69c74374c'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('place_id', sa.Integer(), nullable=True))
    op.drop_constraint('activity_modality_id_fkey', 'activity', type_='foreignkey')
    op.create_foreign_key(None, 'activity', 'place', ['place_id'], ['id'])
    op.drop_column('activity', 'modality_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('modality_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.create_foreign_key('activity_modality_id_fkey', 'activity', 'modality', ['modality_id'], ['id'])
    op.drop_column('activity', 'place_id')
    # ### end Alembic commands ###
