"""activity image column

Revision ID: 701b40463641
Revises: 48fcced7879f
Create Date: 2022-05-28 16:51:47.220904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701b40463641'
down_revision = '48fcced7879f'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'image')
    # ### end Alembic commands ###
