"""activity title column

Revision ID: 896c033c2a21
Revises: 47b2f5981f01
Create Date: 2022-05-31 18:27:09.909678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896c033c2a21'
down_revision = '47b2f5981f01'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('title', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'title')
    # ### end Alembic commands ###
