"""Fixing user column types

Revision ID: 953921a03bff
Revises: 40e8ac22dd25
Create Date: 2022-06-02 23:41:48.870328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953921a03bff'
down_revision = '40e8ac22dd25'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image')
    op.add_column('user', sa.Column('image', sa.Text(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
