"""nullable user fields

Revision ID: d83e0c5ccf5c
Revises: d500a4c01035
Create Date: 2022-04-21 16:32:52.687946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83e0c5ccf5c'
down_revision = 'd500a4c01035'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'picture',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'picture',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('user', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
